import Head from 'next/head';
import { GetServerSidePropsContext } from 'next';
import DefaultLayout from '@/layouts/default';

export default function Home({ data }) {
	void data;
	return (
		<>
			<Head>
				<title>ARE</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DefaultLayout>{null}</DefaultLayout>
		</>
	);
}

// export async function getServerSideProps(ctx: GetServerSidePropsContext) {
// 	void ctx;
// 	return {
// 		props: {
// 			data: [1, 2, 3],
// 		},
// 	};
// }

export async function getStaticProps(ctx: GetServerSidePropsContext) {
	void ctx;
	console.log(ctx);
	return {
		props: {
			data: [1, 2, 3],
		},
	};
}
