import Head from 'next/head';
import { GetServerSidePropsContext } from 'next';
import { getPageData } from './_data';

export default function Home({ data }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>{data}</div>
		</>
	);
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
	return getPageData(ctx);
}
